import { BarChart2, Bomb, CopyPlus, Minus, Trash2 } from "lucide-react";
import {
  HeartIcon,
  User,
  ChevronRight,
  ChevronLeft,
  MoreHorizontal,
  Plus,
  Disc3,
  Library,
  LogOut,
  MessageCircle,
  Settings,
  Bell,
  User2Icon,
  SearchIcon,
  Play,
  MoreVertical,
  ListVideo,
  ListMusic,
  ListPlus,
  Disc,
  Mic2,
  Repeat,
  SkipBack,
  SkipForward,
  Pause,
  Shuffle,
  ChevronUp,
  ChevronDown,
  Sun,
  Moon,
  Globe,
} from "lucide-react";

export const Icons = {
  user: User,
  heart: HeartIcon,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  moreHorizontal: MoreHorizontal,
  plus: Plus,
  disc3: Disc3,
  library: Library,
  listMusic: ListMusic,
  logOut: LogOut,
  messageCircle: MessageCircle,
  settings: Settings,
  bell: Bell,
  user2Icon: User2Icon,
  searchIcon: SearchIcon,
  play: Play,
  moreVertical: MoreVertical,
  listVideo: ListVideo,
  listPlus: ListPlus,
  disc: Disc,
  mic2: Mic2,
  repeat: Repeat,
  skipBack: SkipBack,
  skipForward: SkipForward,
  pause: Pause,
  shuffle: Shuffle,
  sun: Sun,
  moon: Moon,
  minus: Minus,
  bomb: Bomb,
  trash2: Trash2,
  copyPlus: CopyPlus,
  globe: Globe,
  barChart2: BarChart2,
};
