import Nav from "./components/Nav";
import ProvidersWrapper from "./ProvidersWrapper";
import "./globals.css";
import Player from "./components/Player";

export const metadata = {
  title: "Cherry Music",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ProvidersWrapper>
          <Nav />
          {children}
          <Player />
        </ProvidersWrapper>
      </body>
    </html>
  );
}
