import {
  HeartIcon,
  User,
  ChevronRight,
  ChevronLeft,
  MoreHorizontal,
  Plus,
  Disc3,
  Library,
  ListMusic,
  LogOut,
  MessageCircle,
  Settings,
  Bell,
  User2Icon,
  SearchIcon,
  Play,
  MoreVertical,
} from "lucide-react";

export const Icons = {
  user: User,
  heart: HeartIcon,
  chevronRight: ChevronRight,
  chevronLeft: ChevronLeft,
  moreHorizontal: MoreHorizontal,
  plus: Plus,
  disc3: Disc3,
  library: Library,
  listMusic: ListMusic,
  logOut: LogOut,
  messageCircle: MessageCircle,
  settings: Settings,
  bell: Bell,
  user2Icon: User2Icon,
  searchIcon: SearchIcon,
  play: Play,
  moreVertical: MoreVertical,
};
